#!/bin/bash
> helloName.csv
> makeAbba.csv
> makeTags.csv
> makeOutWord.csv
> extraEnd.csv
> firstTwo.csv
> firstHalf.csv
> withoutEnd.csv
> comboString.csv
> nonStart.csv
> left2.csv
> right2.csv
> theEnd.csv
> withouEnd2.csv
> middleTwo.csv
> endsLy.csv
> nTwice.csv
> twoChar.csv
> middleThree.csv
> hasBad.csv
> atFirst.csv
> lastChars.csv
> conCat.csv
> lastTwo.csv
> seeColor.csv
> frontAgain.csv
> minCat.csv
> extraFront.csv
> without2.csv
> deFront.csv
> startWord.csv
> withoutX.csv
> withoutX2.csv
